import type { NextPage } from "next";
import Head from "next/head";
import { useQuery, gql } from "@apollo/client";

const GET_LINKS = gql`
  query GetLinks {
    links {
      title
      address
      user {
        name
      }
    }
  }
`;
interface IUser {
  name: string;
}

interface ILinks {
  title: string;
  address: string;
  user: IUser;
}

interface IGraphqlData {
  links: ILinks[];
}

const Home: NextPage = () => {
  const { loading, error, data } = useQuery<IGraphqlData>(GET_LINKS);

  if (loading) return <div>Loading...</div>;
  if (error) return <div>Error! {error.message}</div>;

  console.log(data);
  return (
    <div>
      <Head>
        <title>GraphQL Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen h-screen">
        <div>Hello world</div>
        <div>
          {data?.links?.map((link) => (
            <div key={link.title}>
              <div>{link.title}</div>
              <div>{link.address}</div>
              <div>{link.user.name}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default Home;
